---
- name: Install haproxy
  apt:
    name: haproxy
    state: present

- name: Deploy haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart haproxy

- name: Ensure haproxy enabled and started
  systemd:
    name: haproxy
    enabled: true
    state: started
